bcc: dmorano@ece.neu.edu (verify test loop-back address)
From: (Dave Morano) dmorano@ece.neu.edu
x-From: (Dave Morano) morano@computer.org
to: (Professor D. Kaeli) dkaeli@ac.upc.es 
to: (Professor A. Uht) uht@ele.uri.edu
to: (Alireza Khalafi) akhalafi@ece.neu.edu
x-to: (Professor David Kaeli) kaeli@ECE.NEU.EDU
Subject: submitted paper

All,

I submitted the paper, pretty much at the end ! :-)

I was able to fix most all comments that I had received as well as fix
most stuff from a final review of the paper.  Unfortunately there are
probably some weak spots that we left in the paper.  As an aside,
running LaTeX at ECE did not seem to clear up that font peculiarity
that we seemed to have when viewed using Acroread.  Fortunately,
the paper graphics quality is still pristine when printed !

We were submission # 126 ! (for what that might mean) :-)

The submitted paper is attached in PDF.

Thanks very much to everyone,
Dave M.
