reply-to: (David Morano) morano@ele.uri.edu
bcc: dmorano@ece.neu.edu (verify test loop-back address)
From: (David Morano) morano@computer.org
to: (Alireza Khalafi) akhalafi@ece.neu.edu
x-cc: (Professor D. Kaeli) dkaeli@ac.upc.es 
x-cc: (Professor Uht) uht@ele.uri.edu
x-to: (Marcos de Alba) mdealba@ECE.NEU.EDU
x-to: (Marcos Ruben de Alba Rosano) mdealba@ccs.neu.edu
x-cc: (Sean Langford) langfors@ele.uri.edu
x-cc: (Thomas Wenisch) iota@ele.uri.edu
x-cc: (S Murat Bicer) mbicer@ECE.NEU.EDU
x-cc: (Maryam Ashouei) mashouei@ece.neu.edu
x-to: black@coe.neu.edu (Jennifer Black)
x-CC: jblack@ece.neu.edu
x-cc: (Deniz Balkan) dbalkan@ece.neu.edu
x-cc: (Prof. David Kaeli) dkaeli@ac.upc.es
x-cc: (Professor David Kaeli) kaeli@ECE.NEU.EDU
Subject: also

Ali,

Can you also supply some words that explain what we learned from
the data in those tables ?  My head is almost totally dried
and I do not really remember what that stuff was about. :-((

Thanks,
Dave M.
