bcc: dmorano@ece.neu.edu (verify test loop-back address)
reply-to: (Dave Morano) morano@ele.uri.edu
From: (Dave Morano) dmorano@ece.neu.edu
to: (Professor D. Kaeli) dkaeli@ac.upc.es 
x-to: (Professor David Kaeli) kaeli@ECE.NEU.EDU
To: (Professor A. Uht) uht@ele.uri.edu
To: (Alireza Khalafi) akhalafi@ece.neu.edu
x-cc: (Marcos de Alba) mdealba@ECE.NEU.EDU
x-cc: (Rajiv Shridhar) rajiv@ECE.NEU.EDU
x-Cc: "Waleed M. Meleis" <meleis@ece.neu.edu>
Subject: improved value speculation handling

Please find enclosed a draft PDF of the idea that we (Ali and I)
have been thinking about for better handling of value speculation.

Dave M.
