From: (David Morano) morano@coe.neu.edu
To: (Professor Uht) <uht@ele.uri.edu>
cc: morano@computer.org (verify test loop-back address)
Subject: here are the updated figures

Gus,

Thanks for correcting example 5.  I noticed it yesterday but
then forgot about it entirely !

I like the idea of a marking DEE executions distinctly from main-line
executions.  I had considered something like (which we may want to
consider later if we do much more complicated examples) :

MX		main-line execution
MR		main-line relay operation
MB		main-line rebroadcast

DX		disjoint path execution
DR		disjoint relay
DB		disjoint rebroadcast

PB		re-prediction of branch
PD		re-prediction of a data value

BT		branch resolved to taken
BN		branch resolved to not-taken

There may even be more of these or refinements of these but we
can think about this stuff some other time !

Thanks,
Dave

