x-reply-to: (David Morano) morano@ele.uri.edu
x-reply-to: (David Morano) dmorano@ece.neu.edu
bcc: morano@ele.uri.edu
x-From: (David Morano) morano@ele.uri.edu
From: (David Morano) morano@ele.uri.edu
to: (Alireza Khalafi) akhalafi@ece.neu.edu
x-cc: (Professor D. Kaeli) dkaeli@ac.upc.es 
x-cc: (Professor Uht) uht@ele.uri.edu
x-cc: (Marcos de Alba) mdealba@ECE.NEU.EDU
x-cc: (Marcos Ruben de Alba Rosano) mdealba@ccs.neu.edu
x-cc: (Sean Langford) langfors@ele.uri.edu
x-cc: (Thomas Wenisch) iota@ele.uri.edu
x-cc: (S Murat Bicer) mbicer@ECE.NEU.EDU
x-cc: (Maryam Ashouei) mashouei@ece.neu.edu
x-to: black@coe.neu.edu (Jennifer Black)
x-CC: jblack@ece.neu.edu
x-cc: (Deniz Balkan) dbalkan@ece.neu.edu
x-cc: (Prof. David Kaeli) dkaeli@ac.upc.es
x-cc: (Professor David Kaeli) kaeli@ECE.NEU.EDU
Subject: draft MEDEA paper

Ali and All,

Please find enclosed the draft MEDEA paper as it stands now.

First up is to check the abstract, if possible, we should try
and submit that by July 3 (maybe they will like us better if we do
-- otherwise it appears to be optional). :-)

I would like to bring the idea into the introduction that we are
addressing the need for single-threaded performace as opposed to
overall throughput performance through software multithreading or
multiprocessing (which appears to be the very hot potato at this year's
MEDEA).  High performance on single-threaded programs is the real
strength of Levo and I think that we should stay with that as
opposed to trying to pretend to be something else (at least for now).
I have not done anything along that line yet but maybe it
could just be a well phrased sentence !  Suggestions are welcomed.

We also need to do something about how we want to present the existing
data.  The existing tables obviously do not fit so we need to either
shrink them or do something else.

On the length of the paper, we are still over the limit.  We need to cut
out about a few paragraphs worth (and maybe a little more depending on
what we want to do with the data presentation).  We are not over the
ten page limit by much but we may want to add some stuff here or there
(it always seems to happen that way). :-)

I already cut out about 4 pages of stuff from the original.  I went
through the paper trying to abbreviate some stuff while clarifying
other things in fewer words (not very easy).  I am out of ideas for the
moment so any suggestions for things to cut or reduce are welcomed.

The paper is in the two-column format for IEEE but I still need
to double check margins and the like (I have the IEEE rules).

Thanks,
Dave M.
