message-id: <rca255749684491582845@rightcore.com>
x-mailer: PCS mkmsg
Date:  8 Sep 2000 17:39:18 EDT
From: (Dave Morano) morano@computer.org
Subject: Dave's phone number
To: (Team Levo ) levo <morano@computer.org>
reply-to: morano@ele.uri.edu
content-lines: 13

Levo Team,

I want to give you all my phone number in case you want to talk to me
about some Levo thing and when email does not quite seem good enough !
My phone number is 1 (781) 388-1799.  I had previously thought that the
NU phones would not allow a call out here but I have been informed that
they do now and it has also been verified.

If it goes to the answering machine, please ALWAYS leave a message
as I may be back in just a few moments or so.

Dave M.
morano@computer.org
