x-reply-to: (David Morano) morano@ele.uri.edu
x-reply-to: (David Morano) dmorano@ece.neu.edu
x-bcc: morano@ele.uri.edu
x-From: (David Morano) morano@ele.uri.edu
From: (David Morano) morano@ele.uri.edu
to: (Alireza Khalafi) akhalafi@ece.neu.edu
x-cc: (Professor D. Kaeli) dkaeli@ac.upc.es 
x-cc: (Professor Uht) uht@ele.uri.edu
x-cc: (Marcos de Alba) mdealba@ECE.NEU.EDU
x-cc: (Marcos Ruben de Alba Rosano) mdealba@ccs.neu.edu
x-cc: (Sean Langford) langfors@ele.uri.edu
x-cc: (Thomas Wenisch) iota@ele.uri.edu
x-cc: (S Murat Bicer) mbicer@ECE.NEU.EDU
x-cc: (Maryam Ashouei) mashouei@ece.neu.edu
x-to: black@coe.neu.edu (Jennifer Black)
x-CC: jblack@ece.neu.edu
x-cc: (Deniz Balkan) dbalkan@ece.neu.edu
x-cc: (Prof. David Kaeli) dkaeli@ac.upc.es
x-cc: (Professor David Kaeli) kaeli@ECE.NEU.EDU
Subject: more results to choose from ! :-)

Ali,

I found the following files that had results from between Nov
16th and Dev 18th.  There seems to be a few different types
of results mixed in all of this.  

As an aside, I just figured out that The TCCA paper used the "with
cache memory" results at the bottom of the file named
'results011218.txt'.

You might want to go through some of these files and see if you
can piece back together what some of this was.  Even if you do not
tell Gus anything (if anything can be known in addition), it might
be good to just remember what all of the different data sets
were about.

Dave M.
